[Server]
Port = 8080
EnableGRPCGateway = true

[Registry]
Service = "mine.namespace.demo"
IP = "127.0.0.1"
Port = 8500

[PromtheusConfig]
Enable = true
Port = 9092

[FrameLogger]
Path = "../log/frame.log"
LogLevel = "info"

[AccessLogger]
Path = "../log/access.log"

[PanicLogger]
Path = "../log/panic.log"

[ServiceLogger]
Path = "../log/service.log"

[[RateLimit]]
Key = "/todo.UitTodo/Add"
Cap = 1
TokensPerSecond = 1