[Server]
Port = 8_080
EnableGRPCGateway = true

[PromtheusConfig]
Enable = true
Port = 9_092

[FrameLogger]
Path = "../log/frame.log"
LogLevel = "info"
LogFileMaxSizeMB = 10
LogFileMaxBackups = 10
LogMaxAgeDays = 10
LogCompress = false

[AccessLogger]
Path = "../log/access.log"

[PanicLogger]
Path = "../log/panic.log"

[ServiceLogger]
Path = "../log/service.log"

[Registry]
Service = "mine.namespace.demo"
IP = "127.0.0.1"
Port = 8_500

[[RateLimit]]
Key = "/todo.UitTodo/Add"
Cap = 1
TokensPerSecond = 1

[Tracing]
Address = "127.0.0.1:4317"
Namespace = "robot_team"
ServiceName = "mine.namespace.demo"
InstanceId = "mine.namespace.demo"
Env = "Test"